
package org.example.server;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "DemoServerService", targetNamespace = "http://server.example.org/", wsdlLocation = "file:/Users/stone/IdeaProjects/workstem/WebServiceDemo/WsClient/src/main/resources/test.wsdl")
public class DemoServerService
    extends Service
{

    private final static URL DEMOSERVERSERVICE_WSDL_LOCATION;
    private final static WebServiceException DEMOSERVERSERVICE_EXCEPTION;
    private final static QName DEMOSERVERSERVICE_QNAME = new QName("http://server.example.org/", "DemoServerService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/Users/stone/IdeaProjects/workstem/WebServiceDemo/WsClient/src/main/resources/test.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        DEMOSERVERSERVICE_WSDL_LOCATION = url;
        DEMOSERVERSERVICE_EXCEPTION = e;
    }

    public DemoServerService() {
        super(__getWsdlLocation(), DEMOSERVERSERVICE_QNAME);
    }

    public DemoServerService(WebServiceFeature... features) {
        super(__getWsdlLocation(), DEMOSERVERSERVICE_QNAME, features);
    }

    public DemoServerService(URL wsdlLocation) {
        super(wsdlLocation, DEMOSERVERSERVICE_QNAME);
    }

    public DemoServerService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, DEMOSERVERSERVICE_QNAME, features);
    }

    public DemoServerService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public DemoServerService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns DemoServer
     */
    @WebEndpoint(name = "DemoServerPort")
    public DemoServer getDemoServerPort() {
        return super.getPort(new QName("http://server.example.org/", "DemoServerPort"), DemoServer.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns DemoServer
     */
    @WebEndpoint(name = "DemoServerPort")
    public DemoServer getDemoServerPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://server.example.org/", "DemoServerPort"), DemoServer.class, features);
    }

    private static URL __getWsdlLocation() {
        if (DEMOSERVERSERVICE_EXCEPTION!= null) {
            throw DEMOSERVERSERVICE_EXCEPTION;
        }
        return DEMOSERVERSERVICE_WSDL_LOCATION;
    }

}
